title: JLCHENA Letters
description: "懷舊與愛的記錄"
baseurl: ""  # 確保這是空的
url: "https://jlchena-letters.com"

permalink: pretty  # 讓 GitHub Pages 處理無 .html 結尾的網址

collections:
  letters:
    output: true
    permalink: /letters/:name/
