title: JLCHENA Letters
description: "懷舊與愛的記錄"
theme: null  # 避免 GitHub Pages 預設主題覆蓋 Jekyll 設定
future: true
timezone: Asia/Taipei
markdown: kramdown
highlighter: rouge

# 啟用 Collections 來確保信件可生成
collections:
  posts:
    output: true
    permalink: /:categories/:year-:month-:day-:title/

# 啟用 Jekyll 外掛（GitHub Pages 允許的外掛）
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# 設定 paginations（如果你的信件很多，可以用這個讓它分頁）
paginate: 10
paginate_path: "/page:num/"

# 排除不需要的檔案（加快 GitHub Pages 部署速度）
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
