title: JLCHENA Letters
description: "懷舊與愛的記錄"
theme: jekyll-theme-primer

# 啟用 Jekyll 插件
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# 確保 Jekyll 解析未來的文章
future: true
timezone: Asia/Taipei

# Markdown 解析器（確保 Liquid 語法解析正確）
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

# 高亮程式碼（若有使用程式碼區塊）
highlighter: rouge

# 設定分頁（若未來使用分頁功能）
paginate: 5
paginate_path: "/page:num/"

# 確保 Jekyll 正確讀取 _posts/ 文章
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
