title: JLCHENA Letters
description: "懷舊與愛的記錄"
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

future: true
timezone: Asia/Taipei
markdown: kramdown
highlighter: rouge

collections:
  posts:
    output: true
